# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes: 
      - pgdata:/var/lib/postgresql/data
    

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes: 
  pgdata:  